# Generated by Django 4.2.19 on 2025-03-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('videofile', models.FileField(upload_to='video/%y')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
