# Generated by Django 4.2.19 on 2025-03-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='video_image',
            field=models.ImageField(default='black_image.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.CharField(default='https://youtu.be/ofIa6cbeV9w?si=ODE9yozURxZcZRuW', max_length=200),
        ),
    ]
